name: air_pollution_bilstm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy==1.24.3
    - tensorflow==2.10.0
    - scikit-learn==1.3.0
    - mlflow==2.8.0
    - matplotlib==3.7.2
    - protobuf==3.20.3
